apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: eventflow
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: eventflow-platform
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.eventflow.svc.cluster.local:9090
        isDefault: true
        editable: false
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.eventflow.svc.cluster.local:16686
        editable: false
