apiVersion: v1
kind: Service
metadata:
  name: alert-engine
  namespace: eventflow
  labels:
    app.kubernetes.io/name: alert-engine
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: eventflow-platform
spec:
  type: { { .Values.alertEngine.service.type } }
  ports:
    - port: { { .Values.alertEngine.service.port } }
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: alert-engine
