apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: eventflow
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: eventflow-platform
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: follower
    - port: 3888
      name: election
  clusterIP: None
  selector:
    app.kubernetes.io/name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: eventflow
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: eventflow-platform
spec:
  ports:
    - port: 2181
      name: client
      targetPort: 2181
  selector:
    app.kubernetes.io/name: zookeeper
