apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: eventflow
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: eventflow-platform
spec:
  type: ClusterIP
  ports:
    - port: 5775
      targetPort: 5775
      protocol: UDP
      name: zk-compact-thrift
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: jaeger-compact
    - port: 6832
      targetPort: 6832
      protocol: UDP
      name: jaeger-binary
    - port: 5778
      targetPort: 5778
      protocol: TCP
      name: config-rest
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: query
    - port: 14250
      targetPort: 14250
      protocol: TCP
      name: grpc
    - port: 14268
      targetPort: 14268
      protocol: TCP
      name: collector
    - port: 14269
      targetPort: 14269
      protocol: TCP
      name: admin
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp-http
  selector:
    app.kubernetes.io/name: jaeger
