apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eventflow

resources:
  - namespace.yaml
  - configmaps
  - secrets
  - infrastructure
  - services
  - observability
  - ingress

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "1.0.0"
